CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    verified BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS donors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    blood_group VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    address VARCHAR(255),
    available BOOLEAN NOT NULL,
    last_donation_date DATE
);

CREATE TABLE IF NOT EXISTS hospitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    address VARCHAR(255),
    verified BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS blood_banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    address VARCHAR(255),
    verified BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS blood_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id BIGINT NOT NULL,
    blood_group VARCHAR(255) NOT NULL,
    units INTEGER NOT NULL,
    urgency VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    note VARCHAR(1000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS request_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blood_request_id BIGINT NOT NULL,
    responder_user_id BIGINT NOT NULL,
    responder_role VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS donation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blood_bank_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    event_date DATE,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    address VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS event_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_event_id BIGINT NOT NULL,
    donor_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_event_enrollment UNIQUE (donation_event_id, donor_id)
);

CREATE TABLE IF NOT EXISTS blood_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blood_bank_id BIGINT NOT NULL,
    blood_group VARCHAR(255) NOT NULL,
    units INTEGER NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_blood_stock_group UNIQUE (blood_bank_id, blood_group)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message VARCHAR(1000) NOT NULL,
    type VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_donors_user') THEN
        ALTER TABLE donors ADD CONSTRAINT fk_donors_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_hospitals_user') THEN
        ALTER TABLE hospitals ADD CONSTRAINT fk_hospitals_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_blood_banks_user') THEN
        ALTER TABLE blood_banks ADD CONSTRAINT fk_blood_banks_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_blood_requests_requester') THEN
        ALTER TABLE blood_requests ADD CONSTRAINT fk_blood_requests_requester FOREIGN KEY (requester_user_id) REFERENCES users(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_request_responses_request') THEN
        ALTER TABLE request_responses ADD CONSTRAINT fk_request_responses_request FOREIGN KEY (blood_request_id) REFERENCES blood_requests(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_request_responses_user') THEN
        ALTER TABLE request_responses ADD CONSTRAINT fk_request_responses_user FOREIGN KEY (responder_user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_donation_events_bank') THEN
        ALTER TABLE donation_events ADD CONSTRAINT fk_donation_events_bank FOREIGN KEY (blood_bank_id) REFERENCES blood_banks(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_event_enrollments_event') THEN
        ALTER TABLE event_enrollments ADD CONSTRAINT fk_event_enrollments_event FOREIGN KEY (donation_event_id) REFERENCES donation_events(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_event_enrollments_donor') THEN
        ALTER TABLE event_enrollments ADD CONSTRAINT fk_event_enrollments_donor FOREIGN KEY (donor_id) REFERENCES donors(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_blood_stock_bank') THEN
        ALTER TABLE blood_stock ADD CONSTRAINT fk_blood_stock_bank FOREIGN KEY (blood_bank_id) REFERENCES blood_banks(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notifications_user') THEN
        ALTER TABLE notifications ADD CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_blood_requests_requester ON blood_requests(requester_user_id);
CREATE INDEX IF NOT EXISTS idx_request_responses_request ON request_responses(blood_request_id);
CREATE INDEX IF NOT EXISTS idx_request_responses_user ON request_responses(responder_user_id);
CREATE INDEX IF NOT EXISTS idx_donation_events_bank ON donation_events(blood_bank_id);
CREATE INDEX IF NOT EXISTS idx_event_enrollments_event ON event_enrollments(donation_event_id);
CREATE INDEX IF NOT EXISTS idx_event_enrollments_donor ON event_enrollments(donor_id);
CREATE INDEX IF NOT EXISTS idx_blood_stock_bank ON blood_stock(blood_bank_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);
